import type { Metadata } from "next";
import { Geist, Geist_Mono, Fjalla_One } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fjallaOne = Fjalla_One({
  variable: "--font-fjalla-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "New Checkout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* MobiPay SDK */}
        <Script
          src="https://sdk.mobibox.io/mobi-pay-sdk.js"
          strategy="beforeInteractive"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fjallaOne.variable} antialiased`}
      >
        {/* ✅ Facebook Pixel (DYNAMIC FROM URL) */}
        <Script id="facebook-pixel-dynamic" strategy="afterInteractive">
          {`
            (function () {
              function getPixel() {
                const params = new URLSearchParams(window.location.search);
                const urlPixel = params.get("fbpixel");
                const stored = sessionStorage.getItem("fbpixel");

                if (urlPixel && /^\\d+$/.test(urlPixel)) {
                  sessionStorage.setItem("fbpixel", urlPixel);
                  return urlPixel;
                }

                if (stored && /^\\d+$/.test(stored)) {
                  return stored;
                }

                return null;
              }

              const pixelId = getPixel();

              if (!pixelId) return;

              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;
              n.push=n;
              n.loaded=!0;
              n.version='2.0';
              n.queue=[];
              t=b.createElement(e);
              t.async=!0;
              t.src=v;
              s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}
              (window, document,'script','https://connect.facebook.net/en_US/fbevents.js');

              fbq('init', pixelId);
              fbq('track', 'PageView');

              setTimeout(function() {
                if (window.fbq && window.fbq.loaded) {
                  console.log('✅ Pixel loaded:', pixelId);
                } else {
                  console.warn('⚠️ Pixel blocked');
                }
              }, 2000);
            })();
          `}
        </Script>

        {/* ✅ Noscript fallback */}
        {/* <Script id="facebook-pixel-noscript" strategy="afterInteractive">
          {`
            (function () {
              const params = new URLSearchParams(window.location.search);
              const pixelId = params.get("fbpixel") || sessionStorage.getItem("fbpixel");
              if (!pixelId) return;

              var img = document.createElement('img');
              img.height = 1;
              img.width = 1;
              img.style.display = 'none';
              img.src = "https://www.facebook.com/tr?id=" + pixelId + "&ev=PageView&noscript=1";
              document.body.appendChild(img);
            })();
          `}
        </Script> */}

        {children}
      </body>
    </html>
  );
}